version: '3.9'
services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=moviedb'
      - 'POSTGRES_PASSWORD=sql'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  movie-api:
    build:
      dockerfile: Dockerfile
    container_name: movie-api-application
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moviedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sql
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./movie_application
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8081:80"

volumes:
  db: