services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=moviedb'
      - 'POSTGRES_PASSWORD=sql'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST=localhost'
    ports:
      - '5432:5432'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-api
    depends_on:
      - db
    ports:
      - "8081:8081"